import { shotCodeAt, parseStatementText, reconcile, balanceFlags } from './src/core.mjs';

const KEY = 'ssonda-mvp-v1';
const $ = (selector, node = document) => node.querySelector(selector);
const money = value => `${Number(value || 0).toLocaleString('ko-KR')}원`;
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const nowText = () => new Date().toLocaleString('sv-SE').replace(' ', 'T').slice(0, 16);
const defaultState = () => ({
  store: { name: '쏜다 파일럿 매장', bank: '은행명', account: '계좌번호를 입력하세요', accountHolder: '' },
  expected: [], deposits: [], decisions: {}, audit: [{ at: new Date().toISOString(), event: 'MVP 시작', detail: '이 브라우저에만 데이터가 저장됩니다.' }], active: 'session'
});
let state = load();
function load(){try{return {...defaultState(), ...JSON.parse(localStorage.getItem(KEY))};}catch{return defaultState()}}
function save(event, detail){ if(event) state.audit.unshift({at:new Date().toISOString(),event,detail}); localStorage.setItem(KEY,JSON.stringify(state)); render(); }
function toast(message){const node=document.createElement('div');node.className='toast';node.textContent=message;document.body.append(node);setTimeout(()=>node.remove(),1800)}
function encode(data){return btoa(unescape(encodeURIComponent(JSON.stringify(data))));}
function decode(value){try{return JSON.parse(decodeURIComponent(escape(atob(value))))}catch{return null}}
function paymentLink(expected){ const payload={v:1,s:state.store.name,b:state.store.bank,a:state.store.account,h:state.store.accountHolder,n:expected.customerName,m:expected.amount,c:expected.code,id:expected.id}; return `${location.origin}${location.pathname}?pay=${encode(payload)}`; }
function getPayment(){return new URLSearchParams(location.search).get('pay');}
function badge(status){const map={candidate:['후보','ok'],review:['검토 필요','warn'],unmatched:['미매칭','bad'],confirmed:['확정','ok'],held:['보류','warn'],excluded:['제외','bad']};const [label,kind]=map[status]||[status,''];return `<span class="badge ${kind}">${label}</span>`}
function header(){return `<header class="brand"><div class="stamp">쏜다</div><div><h1>쏜다 <small class="muted">베타</small></h1><div class="sub">a comma의 계좌이체 입금 대조·정산 확인 도구</div></div></header>`}
function customer(payload){
 const link=location.href; const qr=`/qr?data=${encodeURIComponent(link)}`;
 document.title='쏜다 결제 안내';
 $('#app').innerHTML=`<main class="customer"><div class="card">${header()}<hr/><p><b>${esc(payload.n)}님</b>, 아래 계좌로 <b class="money">${money(payload.m)}</b>을 송금해 주세요.</p><div class="account">${esc(payload.b)} · ${esc(payload.a)}</div><div class="actions"><button class="primary" id="copyAccount">계좌번호 복사</button><button class="secondary" id="share">안내 공유</button></div><hr/><p class="muted">송금자 이름을 수정할 수 있다면 이름 뒤에 아래 번호를 붙여 주세요.</p><div class="code">${esc(payload.c)}</div><p>예: 홍길동${esc(payload.c)}</p><div class="notice">이 화면은 송금을 대신 실행하거나 금액을 보관하지 않습니다. 송금 후 매장 확인을 기다려 주세요.</div><details><summary>QR 안내 보기</summary><img class="qr" src="${qr}" alt="이 결제 안내 링크 QR 코드"/></details></div></main>`;
 $('#copyAccount').onclick=async()=>{await navigator.clipboard.writeText(payload.a);toast('계좌번호를 복사했습니다.')};
 $('#share').onclick=async()=>{if(navigator.share) await navigator.share({title:'쏜다 계좌이체 안내',url:link}); else {await navigator.clipboard.writeText(link);toast('안내 링크를 복사했습니다.')}};
}
function nav(){return `<nav class="tabs">${[['session','1. 세션·기대결제'],['import','2. 입금내역 불러오기'],['review','3. 후보 검토·확정'],['report','4. 정산서·감사기록']].map(([id,label])=>`<button class="${state.active===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</nav>`}
function sessionView(){
 const rows=state.expected.map(e=>`<tr><td>${esc(e.customerName)}</td><td class="money">${money(e.amount)}</td><td><b>${e.code}</b></td><td>${esc(e.issuedAt.replace('T',' '))}</td><td><button class="secondary small" data-link="${e.id}">고객 안내</button> <button class="danger small" data-delete-expected="${e.id}">삭제</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">아직 등록된 기대 결제가 없습니다.</td></tr>';
 return `<section class="grid"><div class="card span-5"><h2>파일럿 매장 설정</h2><div class="form-row"><p><label>매장명</label><input id="storeName" value="${esc(state.store.name)}"/></p><p><label>은행명</label><input id="bank" value="${esc(state.store.bank)}"/></p><p><label>예금주</label><input id="holder" value="${esc(state.store.accountHolder)}"/></p></div><p><label>입금 계좌번호</label><input id="account" value="${esc(state.store.account)}" placeholder="숫자와 하이픈"/></p><button class="primary" id="saveStore">매장 설정 저장</button><div class="notice">이 MVP는 데이터가 이 기기의 브라우저에만 저장됩니다. 실거래 전용 배포나 민감 이미지 보관은 지원하지 않습니다.</div></div><div class="card span-7"><h2>기대 결제 등록</h2><p class="muted">코드는 발급 시각 + 0~9 지터로 생성합니다. 금액은 절대 바꾸지 않습니다.</p><div class="form-row"><p><label>고객 이름</label><input id="customerName" placeholder="예: 홍길동"/></p><p><label>결제 금액</label><input id="expectedAmount" inputmode="numeric" placeholder="예: 35000"/></p><p><label>발급 시각</label><input id="issuedAt" type="datetime-local" value="${nowText()}"/></p></div><button class="primary" id="addExpected">ShotCode 발급 및 고객 안내 만들기</button></div><div class="card span-12"><h2>이번 세션 기대 결제 ${state.expected.length}건</h2><table class="ledger"><thead><tr><th>고객</th><th>금액</th><th>ShotCode</th><th>발급 시각</th><th>동작</th></tr></thead><tbody>${rows}</tbody></table></div></section>`;
}
function importView(){return `<section class="grid"><div class="card span-7"><h2>입금 내역 붙여넣기</h2><p class="muted">은행 앱에서 복사한 표 또는 <code>일시,입금자명,금액,잔액</code> CSV를 붙여넣으세요. 사진 OCR은 실제 파일럿 전 별도 보안 처리로 연결해야 합니다.</p><textarea id="statement" placeholder="일시,입금자명,금액,잔액\n2026-08-28 14:03,홍길동123,35000,1035000"></textarea><div class="actions"><button class="primary" id="parseStatement">내역 추가</button><button class="secondary" id="demoData">안전한 데모 데이터 입력</button><label class="secondary">이미지 선택<input class="hidden" id="imageFile" type="file" accept="image/*"/></label></div><p class="reason" id="importResult"></p></div><div class="card span-5"><h2>현재 불러온 입금 ${state.deposits.length}건</h2><p class="muted">원본 이미지와 붙여넣기 원문은 저장하지 않습니다. 필요한 데이터만 현재 브라우저에 남습니다.</p><button class="danger" id="clearDeposits">입금 내역 모두 삭제</button></div><div class="card span-12"><table class="ledger"><thead><tr><th>일시</th><th>입금자명</th><th>금액</th><th>잔액</th></tr></thead><tbody>${state.deposits.map(d=>`<tr><td>${esc(d.time||'-')}</td><td>${esc(d.sender)}</td><td class="money">${money(d.amount)}</td><td>${d.balance?money(d.balance):'-'}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">불러온 입금 내역이 없습니다.</td></tr>'}</tbody></table></div></section>`}
function reviewView(){
 const {results,unmatchedDeposits}=reconcile(state.expected,state.deposits); const balance=Object.fromEntries(balanceFlags(state.deposits).map(v=>[v.id,v]));
 const rows=results.map(({expected,best})=>{const decision=state.decisions[expected.id];const display=decision?.status||best?.status||'unmatched';const dep=best;return `<tr><td><b>${esc(expected.customerName)}</b><br/><span class="reason">${expected.code} · ${money(expected.amount)}</span></td><td>${dep?`${esc(dep.sender)}<br/><span class="reason">${esc(dep.time||'시각 없음')} · ${money(dep.amount)}</span>`:'-'}</td><td>${badge(display)} ${dep?.flags?.length?`<div class="reason">${dep.flags.join(', ')}</div>`:''}${dep&&balance[dep.id]&&!balance[dep.id].ok?'<div class="reason">잔액 연속성 불일치</div>':''}</td><td>${decision?`<span class="reason">${esc(decision.memo||'')}</span>`:`${dep?`<button class="primary small" data-decision="confirmed:${expected.id}:${dep.id}">확정</button> <button class="secondary small" data-decision="held:${expected.id}:${dep.id}">보류</button>`:'<button class="secondary small" data-decision="held:'+expected.id+':">미매칭 보류</button>'}`}</td></tr>`}).join('');
 return `<section><div class="notice"><b>자동 확정하지 않습니다.</b> 후보는 이름·코드·금액·발급 후 60분을 교차 확인해 제시할 뿐이며, 운영자가 반드시 확정 또는 보류합니다.</div><div class="card"><h2>대조 검토</h2><table class="ledger"><thead><tr><th>기대 결제</th><th>가장 가까운 입금</th><th>근거·플래그</th><th>운영자 결정</th></tr></thead><tbody>${rows||'<tr><td colspan="4" class="muted">기대 결제부터 등록하세요.</td></tr>'}</tbody></table></div><div class="card" style="margin-top:16px"><h3>사용되지 않은 입금 ${unmatchedDeposits.length}건</h3>${unmatchedDeposits.map(d=>`<div>${esc(d.sender)} · ${money(d.amount)} · ${esc(d.time||'시각 없음')}</div>`).join('')||'<span class="muted">없음</span>'}</div></section>`}
function reportView(){const decisions=Object.values(state.decisions);const confirmed=decisions.filter(v=>v.status==='confirmed');const held=decisions.filter(v=>v.status==='held');return `<section class="grid"><div class="card span-12"><div class="kpis"><div class="kpi"><span class="muted">기대 결제</span><b>${state.expected.length}</b></div><div class="kpi"><span class="muted">운영자 확정</span><b>${confirmed.length}</b></div><div class="kpi"><span class="muted">보류</span><b>${held.length}</b></div><div class="kpi"><span class="muted">미결</span><b>${Math.max(0,state.expected.length-decisions.length)}</b></div></div></div><div class="card span-7"><h2>정산서 내보내기</h2><p>확정은 운영자 판단의 기록입니다. 자동 이체, 지급, 환불 기능은 없습니다.</p><button class="primary" id="downloadCsv">CSV 정산서 다운로드</button></div><div class="card span-5"><h2>세션 데이터</h2><button class="danger" id="resetAll">이 기기의 모든 세션 데이터 삭제</button></div><div class="card span-12"><h2>감사 기록</h2><table class="ledger"><thead><tr><th>시각</th><th>행동</th><th>세부</th></tr></thead><tbody>${state.audit.map(v=>`<tr><td>${new Date(v.at).toLocaleString('ko-KR')}</td><td>${esc(v.event)}</td><td>${esc(v.detail)}</td></tr>`).join('')}</tbody></table></div></section>`}
function render(){const pay=decode(getPayment());if(pay){customer(pay);return}document.title='쏜다 베타 | a comma';$('#app').innerHTML=`<main class="shell">${header()}<div class="notice">제한된 매장 파일럿용 로컬 MVP입니다. 이체를 실행·보관하지 않으며, 후보 제시는 운영자 확인 전 정산 확정이 아닙니다.</div>${nav()}<div id="view">${state.active==='session'?sessionView():state.active==='import'?importView():state.active==='review'?reviewView():reportView()}</div></main>`;bind();}
function download(text,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function bind(){
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.active=b.dataset.tab;save()});
 $('#saveStore')?.addEventListener('click',()=>{state.store={name:$('#storeName').value.trim()||'이름 없는 매장',bank:$('#bank').value.trim()||'은행명',account:$('#account').value.trim()||'계좌번호 미입력',accountHolder:$('#holder').value.trim()};save('매장 설정 변경',state.store.name);toast('매장 설정을 저장했습니다.')});
 $('#addExpected')?.addEventListener('click',()=>{const customerName=$('#customerName').value.trim(), amount=Number($('#expectedAmount').value),issued=$('#issuedAt').value;if(!customerName||!amount||!issued){toast('고객 이름, 금액, 발급 시각을 입력하세요.');return}const expected={id:crypto.randomUUID(),customerName,amount,issuedAt:issued,code:shotCodeAt(new Date(issued))};state.expected.push(expected);save('기대 결제 등록',`${customerName} · ${money(amount)} · ${expected.code}`);toast(`ShotCode ${expected.code}을 발급했습니다.`)});
 document.querySelectorAll('[data-delete-expected]').forEach(b=>b.onclick=()=>{const id=b.dataset.deleteExpected;state.expected=state.expected.filter(x=>x.id!==id);delete state.decisions[id];save('기대 결제 삭제',id)});
 document.querySelectorAll('[data-link]').forEach(b=>b.onclick=async()=>{const expected=state.expected.find(x=>x.id===b.dataset.link);const link=paymentLink(expected);await navigator.clipboard.writeText(link);toast('고객 안내 링크를 복사했습니다. 새 탭에서 열어 QR도 표시할 수 있습니다.')});
 $('#parseStatement')?.addEventListener('click',()=>{const parsed=parseStatementText($('#statement').value);state.deposits.push(...parsed.rows);save('입금내역 불러오기',`${parsed.rows.length}건 추가`);toast(`${parsed.rows.length}건을 추가했습니다.`)});
 $('#demoData')?.addEventListener('click',()=>{$('#statement').value='일시,입금자명,금액,잔액\n2026-08-28 14:03,홍길동123,35000,1035000\n2026-08-28 14:08,김민수555,24000,1059000';toast('데모 데이터를 입력했습니다.')});
 $('#imageFile')?.addEventListener('change',()=>toast('이미지 OCR은 이 로컬 MVP 범위에서 비활성화했습니다. 민감 이미지는 업로드하지 말고 표를 붙여넣으세요.'));
 $('#clearDeposits')?.addEventListener('click',()=>{state.deposits=[];save('입금내역 삭제','전체 삭제')});
 document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{const [status,expectedId,depositId]=b.dataset.decision.split(':');const memo=prompt('결정 사유 또는 메모를 남기세요.',status==='held'?'운영자 확인 필요':'') ?? '';state.decisions[expectedId]={status,depositId,memo,at:new Date().toISOString()};save(`운영자 ${status==='confirmed'?'확정':'보류'}`,memo||expectedId);toast('결정을 감사 기록에 남겼습니다.')});
 $('#downloadCsv')?.addEventListener('click',()=>{const lines=['고객,기대금액,ShotCode,결정,입금자명,입금금액,메모'];state.expected.forEach(e=>{const d=state.decisions[e.id]||{};const deposit=state.deposits.find(x=>x.id===d.depositId)||{};lines.push([e.customerName,e.amount,e.code,d.status||'미결',deposit.sender||'',deposit.amount||'',d.memo||''].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))});download('\ufeff'+lines.join('\n'),'ssonda-settlement-report.csv');save('정산서 다운로드',`${state.expected.length}개 기대 결제`)});
 $('#resetAll')?.addEventListener('click',()=>{if(confirm('이 브라우저의 쏜다 세션 데이터를 모두 삭제할까요?')){state=defaultState();save('세션 초기화','전체 로컬 데이터 삭제')}});
}
render();
